# https://yarnpkg.com/configuration/yarnrc
# https://runebook.dev/ko/docs/yarn/configuration/yarnrc

changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

changesetIgnorePatterns:
  - '**/*.test.{js,ts}'
  - '**/*.spec.{js,ts}'

defaultSemverRangePrefix: ''

enableColors: true

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs
